<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $quotation->quotation_number }}</title>
    <style>
        @page {
            margin: 18px 20px 22px;
        }

        body {
            margin: 0;
            color: #111827;
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            line-height: 1.35;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .sheet {
            border: 1px solid #000000;
        }

        .sheet td,
        .sheet th {
            border: 1px solid #000000;
            padding: 5px 6px;
            vertical-align: top;
        }

        .title-row {
            background: #d9d9d9;
            text-align: center;
            font-size: 16px;
            font-weight: 700;
            letter-spacing: 1px;
        }

        .company-cell {
            padding: 8px 10px 10px;
            text-align: center;
        }

        .company-name {
            font-size: 18px;
            font-weight: 700;
            letter-spacing: 0.4px;
        }

        .muted {
            color: #374151;
        }

        .label-cell {
            width: 16%;
            font-weight: 700;
            background: #f5f5f5;
            white-space: nowrap;
        }

        .value-cell {
            width: 21%;
        }

        .logo-cell {
            width: 16%;
            text-align: center;
            vertical-align: middle;
        }

        .logo-cell img {
            max-width: 90px;
            max-height: 52px;
        }

        .recipient-cell {
            min-height: 88px;
        }

        .header-mini {
            font-size: 10px;
        }

        .section-head {
            font-weight: 700;
            background: #efefef;
        }

        .product-table th {
            background: #d9d9d9;
            font-size: 11px;
            font-weight: 700;
            text-align: center;
        }

        .product-table td {
            min-height: 62px;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .product-name {
            font-weight: 700;
        }

        .sub-line {
            display: block;
            margin-top: 3px;
            color: #374151;
            font-size: 10px;
        }

        .notice-row {
            background: #efefef;
            font-weight: 700;
            text-align: center;
            font-size: 12px;
            padding: 12px 8px !important;
        }

        .signature-box {
            min-height: 86px;
            text-align: center;
        }

        .signature-spacer {
            height: 42px;
        }

        .footer-note {
            text-align: right;
            margin-top: 8px;
            font-size: 10px;
            color: #4b5563;
        }

        .notes-box {
            margin-top: 8px;
            border: 1px solid #000000;
            padding: 6px 8px;
        }
    </style>
</head>
<body>
@php
    $currency = $order->currency ?: config('invoice.pdf.currency', 'INR');
    $currencyLabel = $currency === 'INR' ? '₹' : $currency;
    $sellerName = config('invoice.company.name');
    $sellerGstin = config('invoice.company.gstin');
    $sellerStateCode = config('invoice.company.state_code');
    $sellerAddressLines = config('invoice.company.address_lines', []);
    $termsHeading = config('invoice.terms.heading', 'TERMS : E.&O.E.');
    $termsItems = config('invoice.terms.items', []);
    $bankHeading = config('invoice.branding.bank_heading', 'Bank Details:');
    $bankLines = config('invoice.bank.lines', []);
    $signatureNote = config('invoice.branding.signature_note', 'Signature not required.');
    $autoGeneratedText = config('invoice.branding.auto_generated_text', 'Auto-Generated Invoice,');

    $logoAbsolutePath = public_path(config('invoice.company.logo_path', 'upload/icons/biogenixlogo6.PNG'));
    $logoDataUri = null;

    if (is_file($logoAbsolutePath)) {
        $ext = strtolower(pathinfo($logoAbsolutePath, PATHINFO_EXTENSION)) ?: 'png';
        $logoDataUri = 'data:image/'.$ext.';base64,'.base64_encode(file_get_contents($logoAbsolutePath));
    }

    $documentDate = ($order->created_at ?? now())->format('d-M-Y');
    $recipientCompany = $order->company?->name;
    $recipientName = $order->placedByUser?->name ?: 'Customer';
    $recipientEmail = $order->placedByUser?->email ?: '-';
    $recipientPhone = $order->placedByUser?->phone ?: '-';
@endphp

<table class="sheet">
    <tr>
        <td class="title-row" colspan="7">TAX INVOICE</td>
    </tr>
    <tr>
        <td class="logo-cell" rowspan="3">
            @if($logoDataUri)
                <img src="{{ $logoDataUri }}" alt="Logo">
            @endif
        </td>
        <td class="company-cell" colspan="6">
            <div class="company-name">{{ $sellerName }}</div>
            @foreach($sellerAddressLines as $line)
                <div class="muted">{{ $line }}</div>
            @endforeach
        </td>
    </tr>
    <tr class="header-mini">
        <td class="label-cell">GSTIN No.</td>
        <td class="value-cell">{{ $sellerGstin }}</td>
        <td class="label-cell">STATE CODE:</td>
        <td class="value-cell">{{ $sellerStateCode }}</td>
        <td class="label-cell">Date:</td>
        <td class="value-cell">{{ $documentDate }}</td>
    </tr>
    <tr class="header-mini">
        <td class="label-cell">Invoice No.</td>
        <td class="value-cell">{{ $invoiceNumber }}</td>
        <td class="label-cell">Status</td>
        <td class="value-cell" colspan="3">{{ strtoupper($order->status ?: 'completed') }}</td>
    </tr>
    <tr>
        <td class="section-head">M/s</td>
        <td class="recipient-cell" colspan="4">
            <div><strong>{{ $recipientName }}</strong></div>
            @if($recipientCompany)
                <div>{{ $recipientCompany }}</div>
            @endif
            <div>{{ $recipientEmail }}</div>
            <div>{{ $recipientPhone }}</div>
        </td>
        <td class="section-head">Kind Attn:</td>
        <td>
            <div>{{ $recipientName }}</div>
            <div class="muted">{{ $recipientPhone }}</div>
        </td>
    </tr>
</table>

<table class="sheet product-table" style="margin-top:-1px;">
    <thead>
        <tr>
            <th style="width:10%;">S. No.</th>
            <th style="width:46%;">Product</th>
            <th style="width:16%;">Pack Size</th>
            <th style="width:16%;">Rate</th>
            <th style="width:12%;">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($order->items as $item)
            <tr>
                <td class="text-center">{{ $loop->iteration }}</td>
                <td>
                    <div class="product-name">{{ $item->product_name }}</div>
                    @if($item->variant_name)
                        <span class="sub-line">Model / Variant: {{ $item->variant_name }}</span>
                    @endif
                    @if($item->sku)
                        <span class="sub-line">SKU: {{ $item->sku }}</span>
                    @endif
                    <span class="sub-line">Ordered Qty: {{ number_format((float) $item->quantity, 0) }}</span>
                </td>
                <td class="text-center">
                    <div>{{ number_format((float) $item->quantity, 0) }} Unit{{ (float) $item->quantity > 1 ? 's' : '' }}</div>
                    <span class="sub-line">Pack / Order</span>
                </td>
                <td class="text-center">
                    {{ $currencyLabel }} {{ number_format((float) $item->unit_price, 2) }} / Unit
                </td>
                <td class="text-center">
                    {{ $currencyLabel }} {{ number_format((float) $item->total_amount, 2) }}
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

<table class="sheet" style="margin-top:-1px;">
    <tr>
        <td class="notice-row">Grand Total: {{ $currencyLabel }} {{ number_format((float) $order->total_amount, 2) }}</td>
    </tr>
</table>

<table class="sheet" style="margin-top:-1px;">
    <tr>
        <td style="width:68%;">
            <div><strong>{{ $termsHeading }}</strong></div>
            @foreach($termsItems as $termIndex => $termText)
                <div style="margin-top:4px;">{{ $termIndex + 1 }}. {{ $termText }}</div>
            @endforeach
        </td>
        <td class="signature-box" style="width:32%;">
            <div><strong>For {{ $sellerName }}</strong></div>
            <div class="signature-spacer"></div>
            <div>Authorised Signatory</div>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <strong>{{ $bankHeading }}</strong>
            @foreach($bankLines as $bankLine)
                <div style="margin-top:4px;">{{ $bankLine }}</div>
            @endforeach
        </td>
    </tr>
</table>

@if($order->notes)
    <div class="notes-box">
        <strong>Customer Notes:</strong> {{ $order->notes }}
    </div>
@endif

<div class="footer-note">
    <div>{{ $autoGeneratedText }}</div>
    <div>{{ $signatureNote }}</div>
</div>
</body>
</html>
